spring.application.name=secure-login
server.port=8080

spring.datasource.url=jdbc:h2:mem:securedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


app.jwt.secret=YourSuperSecretJWTKeyThatIsAtLeast256BitsLongForHS256Algorithm
app.jwt.expiration-ms=86400000


app.otp.expiry-minutes=5
app.otp.length=6


app.encryption.key=SecureVault@2024!


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your-email@gmail.com
spring.mail.password=your-app-password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.otp.simulate=true

logging.level.com.secureapp=DEBUG

